// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpfx

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ovpnmonEvent struct {
	_          structs.HostLayout
	TsNs       uint64
	ClientIp   uint32
	RemoteIp   uint32
	ClientId   uint32
	RemotePort uint16
	ClientPort uint16
	PayloadLen uint16
	Type       uint8
	Proto      uint8
	Payload    [512]uint8
	_          [4]byte
}

type ovpnmonFlowKey struct {
	_          structs.HostLayout
	ClientIp   uint32
	RemoteIp   uint32
	RemotePort uint16
	Proto      uint8
	Pad        uint8
}

type ovpnmonFlowStat struct {
	_           structs.HostLayout
	TxBytes     uint64
	TxPackets   uint64
	RxBytes     uint64
	RxPackets   uint64
	FirstNs     uint64
	LastNs      uint64
	Connections uint32
	ClientId    uint32
}

type ovpnmonSessionInfo struct {
	_        structs.HostLayout
	ClientId uint32
	Pad      uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ovpnmonMapEvents          = "events"
	ovpnmonMapFlows           = "flows"
	ovpnmonMapProbeStats      = "probe_stats"
	ovpnmonMapScratch         = "scratch"
	ovpnmonMapSessions        = "sessions"
	ovpnmonProgOvpnmonEgress  = "ovpnmon_egress"
	ovpnmonProgOvpnmonIngress = "ovpnmon_ingress"
	ovpnmonVarVpnMask         = "vpn_mask"
	ovpnmonVarVpnNet          = "vpn_net"
)

// loadOvpnmon returns the embedded CollectionSpec for ovpnmon.
func loadOvpnmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OvpnmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ovpnmon: %w", err)
	}

	return spec, err
}

// loadOvpnmonObjects loads ovpnmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ovpnmonObjects
//	*ovpnmonPrograms
//	*ovpnmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOvpnmonObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadOvpnmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ovpnmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ovpnmonSpecs struct {
	ovpnmonProgramSpecs
	ovpnmonMapSpecs
	ovpnmonVariableSpecs
}

// ovpnmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ovpnmonProgramSpecs struct {
	OvpnmonEgress  *ebpf.ProgramSpec `ebpf:"ovpnmon_egress"`
	OvpnmonIngress *ebpf.ProgramSpec `ebpf:"ovpnmon_ingress"`
}

// ovpnmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ovpnmonMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	Flows      *ebpf.MapSpec `ebpf:"flows"`
	ProbeStats *ebpf.MapSpec `ebpf:"probe_stats"`
	Scratch    *ebpf.MapSpec `ebpf:"scratch"`
	Sessions   *ebpf.MapSpec `ebpf:"sessions"`
}

// ovpnmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ovpnmonVariableSpecs struct {
	VpnMask *ebpf.VariableSpec `ebpf:"vpn_mask"`
	VpnNet  *ebpf.VariableSpec `ebpf:"vpn_net"`
}

// ovpnmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOvpnmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type ovpnmonObjects struct {
	ovpnmonPrograms
	ovpnmonMaps
	ovpnmonVariables
}

func (o *ovpnmonObjects) Close() error {
	return _OvpnmonClose(
		&o.ovpnmonPrograms,
		&o.ovpnmonMaps,
	)
}

// ovpnmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOvpnmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type ovpnmonMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	Flows      *ebpf.Map `ebpf:"flows"`
	ProbeStats *ebpf.Map `ebpf:"probe_stats"`
	Scratch    *ebpf.Map `ebpf:"scratch"`
	Sessions   *ebpf.Map `ebpf:"sessions"`
}

func (m *ovpnmonMaps) Close() error {
	return _OvpnmonClose(
		m.Events,
		m.Flows,
		m.ProbeStats,
		m.Scratch,
		m.Sessions,
	)
}

// ovpnmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOvpnmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type ovpnmonVariables struct {
	VpnMask *ebpf.Variable `ebpf:"vpn_mask"`
	VpnNet  *ebpf.Variable `ebpf:"vpn_net"`
}

// ovpnmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOvpnmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type ovpnmonPrograms struct {
	OvpnmonEgress  *ebpf.Program `ebpf:"ovpnmon_egress"`
	OvpnmonIngress *ebpf.Program `ebpf:"ovpnmon_ingress"`
}

func (p *ovpnmonPrograms) Close() error {
	return _OvpnmonClose(
		p.OvpnmonEgress,
		p.OvpnmonIngress,
	)
}

func _OvpnmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ovpnmon_bpfel.o
var _OvpnmonBytes []byte
